version: '3.9'
services:
  aplication:
    build:
      context: .
    ports:
      - "80:80"
    networks:
      orderCraft-network:
        ipv4_address: 172.30.0.3
  database:
    image: 'postgres:15.2'
    container_name: 'orderCraft-database'
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password32145
    logging:
      options:
        max-size: 10m
        max-file: "3"
    ports:
      - '5448:5432'
    networks:
      orderCraft-network:
        ipv4_address: 172.30.0.2
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
      - ./database/sql/createDatabase.sql:/docker-entrypoint-initdb.d/00_createDatabase.sql
      - ./database/sql/functions.sql:/docker-entrypoint-initdb.d/01_functions.sql
      - ./database/sql/schema.sql:/docker-entrypoint-initdb.d/02_schema.sql
      - ./database/sql/triggers.sql:/docker-entrypoint-initdb.d/03_triggers.sql
      - ./database/sql/insertRole.sql:/docker-entrypoint-initdb.d/04_insertRole.sql
      - ./database/sql/insertUser.sql:/docker-entrypoint-initdb.d/05_insertUser.sql

networks:
  orderCraft-network:
    name: "orderCraft-network"
    ipam:
      config:
        - subnet: 172.30.0.0/24
