version: '3.9'
services:
  backend:
    build: .
    ports:
      - "8080:8080"
    volumes:
      - ./src:/var/www/html
    networks:
      orderCraft-network:
        ipv4_address: 172.30.0.3
networks:
  orderCraft-network:
    name: "orderCraft-network"
    ipam:
      config:
        - subnet: 172.30.0.0/24