version: '3.9'
networks:
  orderCraft-network:
    name: "orderCraft-network"
    ipam:
      config:
        - subnet: 172.30.0.0/24
services:
  orderCraft:
    image: 'postgres:15.2'
    container_name: 'orderCraft-database'
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password32145 # for local test
    logging:
      options:
        max-size: 10m
        max-file: "3"
    ports:
      - '5448:5442'
    networks:
      orderCraft-network:
        ipv4_address: 172.30.0.2
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
      - ./sql/createDatabase.sql:/docker-entrypoint-initdb.d/00_createDatabase.sql
      - ./sql/functions.sql:/docker-entrypoint-initdb.d/01_functions.sql
      - ./sql/schema.sql:/docker-entrypoint-initdb.d/02_schema.sql
      - ./sql/triggers.sql:/docker-entrypoint-initdb.d/03_triggers.sql
